### ISSUE TITLE
v0.2.24 build failing (on MacOS)

### ISSUE THREAD

**Issue by snluu** [time-rs/time#303] opened 2021-01-10 05:38 UTC
Hello! I'm writing to report that v0.2.24 is failing to build (failed on MacOS, have not tried the other platforms yet). Builds v0.1 just fine. Please let me know if there's any other info I can help provide.

`rustc 1.49.0 (e1884a8e3 2020-12-29)`

```
error[E0624]: associated function `to_mmp` is private
  --> /Users/x/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.24/build.rs:30:69
   |
30 |         Some((version, channel, _)) if channel.is_dev() => (version.to_mmp().1 - 2, channel),
   |                                                                     ^^^^^^ private associated function

error[E0624]: associated function `to_mmp` is private
  --> /Users/x/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.24/build.rs:31:73
   |
31 |         Some((version, channel, _)) if channel.is_nightly() => (version.to_mmp().1 - 1, channel),
   |                                                                         ^^^^^^ private associated function

error[E0624]: associated function `to_mmp` is private
  --> /Users/x/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.24/build.rs:32:49
   |
32 |         Some((version, channel, _)) => (version.to_mmp().1, channel),
   |                                                 ^^^^^^ private associated function
```

**Comment by jhpratt** [comment] 2021-01-10 05:40
Please search before creating an issue. This is a duplicate of #295 and #300.

**Closed by jhpratt** 2021-01-10 05:40 UTC

**Comment by snluu** [comment] 2021-01-10 05:45
Ah sorry about that.
