### ISSUE TITLE
Bugged Add<StdDuration> for OffsetDateTime

### ISSUE THREAD

**Issue by jean-airoldie** [time-rs/time#252] opened 2020-05-02 17:37 UTC
Using time = "0.2.13", the following panics.

```rust
use time::{
    OffsetDateTime, NumericalStdDurationShort,
};

fn main() {
    let now = OffsetDateTime::now_utc();
    let dur = 100.milliseconds();

    let later = now + dur;
    let delta = later - now;

    assert_eq!(delta, dur);
}
```

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Duration { seconds: 0, nanoseconds: 0 }`,
 right: `100ms`', src/main.rs:12:5
```

**Comment by jean-airoldie** [comment] 2020-05-02 17:40
In case this matters, here is my current time:
```
[src/main.rs:10] now = OffsetDateTime {
    utc_datetime: PrimitiveDateTime {
        date: Date {
            year: 2020,
            ordinal: 123,
        },
        time: Time {
            hour: 17,
            minute: 37,
            second: 42,
            nanosecond: 840707054,
        },
    },
    offset: UtcOffset {
        seconds: 0,
    },
}
```

**Comment by jean-airoldie** [comment] 2020-05-02 17:43
Moreover it seems like the `Add<time::Duration> for OffsetDateTime` is fine.

**Comment by jhpratt** [comment] 2020-05-02 17:57
Confirmed and investigating.

**Comment by jhpratt** [comment] 2020-05-02 18:09
Looks like I neglected to take subsecond values into account when adding `core::time::Duration`. This should be fixed in the latest commit. I'll publish as v0.2.14 as soon as CI passes.

**Closed** 2020-05-02 18:09 UTC
Labels: bug

**Comment by jhpratt** [comment] 2020-05-02 18:15
Released.
