### ISSUE TITLE
How do I get the Next month?

### ISSUE THREAD

**Issue by mocsy** [time-rs/time#242] opened 2020-04-10 17:55 UTC
How do I get the `next month` or say `three months from now`?

This skips February, and occasionally those which are 30 days only:
```rust
time::OffsetDateTime::now() + time::Duration::days(31);
```

**Comment by jhpratt** [comment] 2020-04-10 18:02
This will be implemented in the form of a `Period` type in the future. The problem is simple: when is one month from January 31? It's not clear what this _should_ be — the implementation wouldn't be too difficult.

**Comment by mocsy** [comment] 2020-04-11 10:31
A possible question is `Which month is the next?` and `Which month is the second next?`.
Potentially an `iter` type?

One would still need to answer `When is one month from January 31?`, but only if there is a need for knowing the exact day.

**Comment by jhpratt** [comment] 2020-04-12 00:00
Well, getting the next month is trivial — just use `.getMonth()` and add one (wrapping if necessary). I assumed you wanted the day as well.

For reference, my current thought is when a `Period` type is implemented, the days will saturate. So 2020-01-31 + 1 month = 2020-02-29.

**Comment by mocsy** [comment] 2020-04-14 17:56
Unfortunately it's not clear for me how to add one to `.getMonth()`.

In fact I didn't even see it in the documentation.
https://time-rs.github.io/time/time/index.html?search=getMonth

The first thing for me was to use time::Duration, but it doesn't have `months()` the largest is `weeks()`.

Would you mind to elaborate a bit on how would implement adding one month?

For the record, I like your Period type idea much, and am looking forward to it.

**Comment by jhpratt** [comment] 2020-04-14 19:18
The method is just `.month()`, and it returns an integer. I was just typing it off-hand without checking actual method names.

A `Duration` of months makes no sense, as it's ultimately stored in seconds, and months vary in length.

**Comment by puetzp** [comment] 2020-12-30 10:22
If you're only interested in the month, using `.month` and just adding one (or three) and implement the wrapping yourself is certainly viable. If you need to create a new `Date` object from it, it becomes a little more complex, as you also need to wrap the days and years. 
That said, it's great to hear that you intend to implement a `Period` type to help solving this kind of problem, @jhpratt. Looking forward to it, as well!
I would second your idea to saturate the days at the end of the month:
When it's mid-January and I say 'one month from now' I refer to the same period in February and would expect a method to return the same day of this month.
Similarly, by saying "in three month" on the 31st of january , I would refer to the end of April (the 30th) and not wrap to the next month. That said, I'm not a native speaker, so the english `Period`  might differ from my understanding of the word.

As an anecdote: The online banking web app I use allows to schedule regular transactions to happen "at the end of the month". I obviously expect it to transfer money at the end of the month, irregardless of the number of days of this specific month.

**Comment by jhpratt** [comment] 2021-06-02 22:12
Just a status update. Time 0.3 will contain a `Month` enum that includes `previous` and `next` methods.

[Reference for v0.3.0-alpha-1](https://docs.rs/time/0.3.0-alpha-1/time/enum.Month.html)

**Comment by jhpratt** [comment] 2021-06-13 03:55
Closing as this will be part of v0.3 and has already been implemented.

**Closed by jhpratt** 2021-06-13 03:55 UTC
Labels: A-core, C-feature-request, C-question
