### ISSUE TITLE
impl Default for OffsetDateTime and PrimitiveDateTime

### ISSUE THREAD

**Issue by acim** [time-rs/time#370] opened 2021-10-24 09:27 UTC
This would be nice to have as serde complains in some situations that this is missing.

**Comment by jhpratt** [comment] 2021-10-31 09:04
Closing as there's not a single obvious default value. My planned RFC will let you use whatever default you'd like and wouldn't be restricted to just the time crate.

**Closed by jhpratt** 2021-10-31 09:04 UTC
Labels: wontfix, C-feature-request, A-core

**Comment by Kinrany** [comment] 2022-02-08 18:14
There doesn't *need* to be an obvious default value, no? The trait makes no guarantees about the default value, other than that it's a valid value. I don't think it would be against the trait spec to even change the value, even though most types that implement the trait may want to make stronger guarantees.

**Comment by jhpratt** [comment] 2022-02-08 20:02
It is generally expected that the default value remain unchanged.

**Comment by frederikhors** [comment] 2022-09-25 22:43
@jhpratt Where is the RFC? Is there any news for this?

**Comment by jhpratt** [comment] 2022-09-25 22:46
I have some significant revisions that need to be made with it, as it grew in scope a fair amount since I first proposed it. I am currently working on an unrelated RFC, but revisiting that is next up on my list.

**Comment by frederikhors** [comment] 2022-09-25 22:48
Ok. Can I open an issue to prevent it from being lost? Or do you want to reopen this?

**Comment by jhpratt** [comment] 2022-09-25 22:51
The RFC is unrelated to `time`, so there's no reason to open an issue here for it.

**Comment by frederikhors** [comment] 2022-09-25 23:09
Then I don't understand what it means that you want to open an RFC for the default of these structs.

It is very useful to have the default of these values because there are often a lot of structs with "derive(Default)" in so many projects.

How can we trace this "feature"? With a new issue?

This is what I'm asking...

I did not understand the answer.

**Comment by jhpratt** [comment] 2022-09-25 23:17
The RFC is not for the default values of these structs. That is a decision I make, and one that I made to _not_ do it. This is because there is no single, obvious default. The RFC is to let _you_, as a downstream user, to set a default value for a field in a different struct. It will be a language feature provided by the compiler, not `time`.

Right now, there is no open PR with the RFC text. What I've just told you is the most up-to-date thing publicly available. It's at the top of my RFC priority list once I finish the one I am working on now. Keep in mind that the RFC being proposed does not mean it will be accepted. Even if it is accepted, it still has to be implemented before eventually being stabilized. This is a drawn out process by design, as language changes cannot be undone (generally speaking). Until the rewritten RFC is posted, the text is not yet public.

**Comment by Kinrany** [comment] 2022-12-26 22:50
Having ran into this again, a default value that does not satisfy everyone seems preferable to no default value at all.

There are N + 1 groups of stakeholders here:

 * N groups that want to use `Default::default()` and similar functions directly to construct their preferred values, be it 0000, 1970 or 2000.
 * Those who want to derive `Default`.

Currently the best alternatives to doing that are:
 * Using functions that return the preferred values directly or with standard functions like `.unwrap_or_else(foo)`.
 * Implementing `Default` manually or using a custom derive macro.

Seeing how you've already decided to not have a default value, I argue that it would now be a strict improvement to overturn that decision and choose any value at all, unilaterally and without trying to reach consensus. One of the N opinionated groups will get what they want, but, more importantly, all the people who just want to `derive(Default)` will be able to do so without using a whole separate dependency.

Changing the default value later would require bumping the major version. If a major version bump is sufficiently undesirable that it would not be worth the change, then there would be no way to change the default value later. However, having that problem would *still* be preferable to not having a default value at all.

Suppose that at some point in the future an RFC for overriding the default value will be written, accepted and implemented. I would argue that that implementation will be able to handle types that already implement `Default`, because otherwise it would be useless for the vast majority of types that already implement `Default`. Therefore these are two completely orthogonal concerns: adding a `Default` impl will not get in the way of the RFC, and the RFC will solve the problem for the N - 1 groups not satisfied by the chosen value.

**Comment by aldanor** [comment] 2022-12-27 13:20
> @jhpratt This is because there is no single, obvious default

> @Kinrany One of the N opinionated groups will get what they want, but, more importantly, all the people who just want to derive(Default) will be able to do so without using a whole separate dependency.

Exactly. Personally, I wouldn't mind (and it looks like I'm not the only one) if the default value was equal to 42 – whatever it is, as long as it enables deriving Default.

Implementing Default with ANY sensible value is always a net positive:

1. Users who want to derive Default would npwbe able to do so; *some* people who agree with that

**Comment by CryZe** [comment] 2022-12-27 13:21
That sounds more like an ergonomics problem of the derive rather than anything.

**Comment by aldanor** [comment] 2022-12-28 21:33
> Actually doesn't your whole argument break down when you consider Option? Cause your arbitrary value that can be derived is `Option<OffsetDateTime>`.

Not really. If I know for sure that during the normal runtime the value is set, I don't want to deal with unwraps or matches or extra branching for that matter. You could have examples where you need that `Default` for convenience just during some weird initialization phase.

Or maybe you just want the `std::mem::take()` to work without providing an explicit value to swap. You could think of many potential use cases where you need `Default` for whichever reason and it's not an `Option` semantically.

**Comment by frederikhors** [comment] 2022-12-30 14:01
Please, can we add the Default value behavior? Please... https://github.com/launchbadge/sqlx/discussions/2260

**Comment by jhpratt** [comment] 2023-01-03 00:01
> unilaterally and without trying to reach consensus.

Absolutely not. Doing something because some people want it while ignoring the issues that it will cause is simply unacceptable.

> Changing the default value later would require bumping the major version. If a major version bump is sufficiently undesirable that it would not be worth the change, then there would be no way to change the default value later.

This is a reason _not_ to have a default value. `time` is a core crate in the Rust ecosystem. I do not take breaking changes lightly, as making one requires an ecosystem-wide upgrade to be fully effective.

> Those users who don't agree with the choice of the default value don't win or lose anything

It will be a source of confusion, which is undesirable.

> That sounds more like an ergonomics problem of the derive rather than anything. Maybe the #[default] attribute can be used (which already exists) to specify the value of each field.

This is sort of what the RFC is, once I eventually get around to finishing the rewrite. More specifically, it will permit this (among other things)

```rust
#[derive(Default)]
struct Foo {
    bar: OffsetDateTime = datetime!(1970-01-01),
}
```

@frederikhors That discussion does not show (at all) how it is related to this discussion.

**Comment by taksedo** [comment] 2023-01-22 19:45
Because of no default implementation I cannot use such a nice approach of derive new:
``` rust
#[derive(new, Default, PartialEq, Eq, Serialize, Deserialize, Debug, Clone)]
pub struct TestEvent {
    #[new(value = "EventId::generate()")]
    id: EventId,
    #[new(value = "OffsetDateTime::now_utc()")]
    created: OffsetDateTime,
}
```

The code returns an error:

```
error[E0277]: the trait bound `OffsetDateTime: Default` is not satisfied
  --> src\common\types\base\domain_event.rs:11:5
   |
6  | #[derive(new, PartialEq, Eq, Serialize, Deserialize, Debug, Clone, Default)]
   |                                                                    ------- in this derive macro expansion
...
11 |     created: OffsetDateTime,
   |     ^^^^^^^^^^^^^^^^^^^^^^^ the trait `Default` is not implemented for `OffsetDateTime`
   |
   = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by CryZe** [comment] 2023-01-22 19:58
@taksedo Deriving Default there wouldn't match the semantics of `new` which would be very unexpected.

**Comment by jhpratt** [comment] 2023-01-22 20:55
For anyone that wishes to comment, please address the fact that there is no single, obvious default value. Saying "just pick one" without reasoning, explanation, etc. will get you nowhere.

This issue was closed for a reason that has been clearly stated and reiterated. **If people continue to say "I want this" without addressing the reason it was closed, I'm just going to lock this issue.** It's not worth my time to endlessly restate the same thing.

**Comment by utkarshgupta137** [comment] 2023-01-23 12:06
> It's worth noting that not even `Time` or `UtcOffset` implement `Default`, despite having more obvious prospective default values.
> 
> There are a [large number of possible epochs](https://en.wikipedia.org/wiki/Epoch_(computing)#Notable_epoch_dates_in_computing) to choose from. Sure, the Unix epoch may make sense to you and me, but that's not the case for everyone.
> 
> Ultimately I plan on writing an RFC that would permit users to override (or set) the default value when `#[derive(Default)]` is used.
> 
> You mention that serde complains. What does this have to do with having a `Default` impl?

Since it hasn't been mentioned, the [derivative](https://mcarton.github.io/rust-derivative/latest/Default.html#setting-the-value-of-a-field) crate provides the custom Default functionality. Playground [example](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=d4cc1bb12808898e3945100fab602c62).
