### ISSUE TITLE
OffsetDateTime -> PrimitiveDateTime

### ISSUE THREAD

**Issue by inf0rm4tik3r** [time-rs/time#553] opened 2023-02-18 13:25 UTC
We can use `assume_utc` and others to convert a `PrimitiveDateTime` to an `OffsetDateTime`.
But there does not seem to be an easy way of converting back to a `PrimitiveDateTime`, that means: simply dropping the offset information.

Use case: Use `PrimitiveDateTime` for something like a database field, at which no offset information is required (UTC always implied). We still want to use "now" functions. As there is only `OffsetDateTime::now_utc()` and no `PrimitiveDateTime::now_***()`, a conversion only seems possible with
```
{
    let now = time::OffsetDateTime::now_utc();
    time::PrimitiveDateTime::new(now.date(), now.time())
}
```

I think there should either be a `From`/`Into` implementation or an appropriately named function for some or both types, which lets you do this using a single function call.

**Comment by jhpratt** [comment] 2023-02-18 23:09
Duplicate of #369, #390, #395, #454, and #458.

**Closed by jhpratt** 2023-02-18 23:09 UTC
